from .clinical_sessions import ClinicalSessionAPIView, ClinicalSessionsForPatientView, ClinicalSessionUpdateAPIView
from .exercises import ExerciseCreateAPIView, ExerciseUpdateAndDeleteAPIView
from .images import ImageDetailsAndDeleteAPIView, ImagesWithTagAPIView, ImageCreateAPIView
from .videos import VideoUploadView, VideoDeleteAPIView
