# Generated by Django 2.2.1 on 2019-06-12 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('password', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dayOfBirth', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateTimeField()),
                ('toDate', models.DateTimeField()),
                ('periodiciy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kinesioapp.Homework')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('cuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kinesioapp.CUser')),
                ('license', models.CharField(max_length=100)),
            ],
            bases=('kinesioapp.cuser',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('cuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kinesioapp.CUser')),
                ('startDate', models.DateTimeField()),
                ('finishDate', models.DateTimeField()),
            ],
            bases=('kinesioapp.cuser',),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('F', 'FINISHED'), ('C', 'CANCELLED')], default='PENDING', max_length=100)),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kinesioapp.Image')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinesioapp.Medic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinesioapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('numberOfHomeworkSession', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('D', 'DONE'), ('C', 'CANCELLED')], default='PENDING', max_length=100)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinesioapp.Exercise')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='exercises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinesioapp.HomeworkExercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='videos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinesioapp.Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kinesioapp.Medic'),
        ),
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('F', 'FINISHED'), ('C', 'CANCELLED')], default='PENDING', max_length=100)),
                ('sessions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinesioapp.Session')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinesioapp.Medic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinesioapp.Patient')),
            ],
        ),
    ]
