# Generated by Django 2.2.1 on 2019-05-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinesioapp', '0002_auto_20190524_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(to='kinesioapp.Topic'),
        ),
    ]
